name: ci-01

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Escribir texto
        run: |
          echo Este texto se escribe al ejecutar el workflow
